title: Project
type: object
additionalProperties: false
required:
  - kind
  - name
  - files
  - variables
properties:
  kind:
    const: "Project"
  name:
    $ref: "./partials/name.yaml"
  files:
    type: array
    items:
      type: string
      minLength: 1
  variables:
    type: object
    patternProperties:
      "^[a-zA-Z][a-zA-Z0-9]*$":
        type: string
